---
controller_credentials:
- name: ServiceNow ITSM Credential - Ames
  description: ServiceNow ITSM Credential
  organization: "{{ my_organization }}"
  credential_type: ServiceNow ITSM Credential
  inputs:
    instance: "{{ snow_url }}"
    username: "{{ snow_username }}"
    password: "{{ servicenow_passwd }}"

- name: AWS Blank Open Environment pvwk8
  organization: "{{ my_organization }}"
  credential_type: Amazon Web Services
  inputs:
    username: "{{ aws_access_key }}"
    password: "{{ aws_secret_key }}"

- name: AWS Machine Credential - Ames
  description: ssh key based authentication
  organization: "{{ my_organization }}"
  credential_type: Machine
  inputs:
    username: ec2-user
    ssh_key_data: "{{ ssh_priv_key }}"
    become_method: sudo

- name: my api tokens - Ames
  organization: "{{ my_organization }}"
  description: Demo custom Credentials
  credential_type: My API KEYS
  inputs:
    DYNATRACE_API_KEY: "{{ dyna_key }}"

- name: Eric Ames
  organization: "{{ my_organization }}"
  credential_type: Vault
  inputs:
    vault_password: "{{ vault_passwd }}"

- name: Mail Server - Ames
  organization: "{{ my_organization }}"
  credential_type: Mail Server
  inputs:
    smtp_server: "smtp.office365.com"
    smtp_port: "587"
    smtp_username: "{{ smtp_username }}"
    smtp_password: "{{ smtp_password }}"

- name: Red Hat Customer Portal - Ames
  organization: "{{ my_organization }}"
  credential_type: Red Hat Customer Portal
  inputs:
    user: "{{ redhat_username }}"
    password: "{{ redhat_passwd }}"

# - name: Red Hat Automation Hub - Certified - Ames
#   organization: "{{ my_organization }}"
#   credential_type: "Ansible Galaxy/Automation Hub API Token"
#   inputs:
#     url: "https://console.redhat.com/api/automation-hub/content/published/"
#     auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
#     token: "{{ red_hat_auto_hub_token }}"

# - name: Red Hat Automation Hub - Validated - Ames
#   organization: "{{ my_organization }}"
#   credential_type: "Ansible Galaxy/Automation Hub API Token"
#   inputs:
#     url: "https://console.redhat.com/api/automation-hub/content/validated/"
#     auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
#     token: "{{ red_hat_auto_hub_token }}"

- name: Daily Demo Windows - Ames
  organization: "{{ my_organization }}"
  credential_type: Machine
  inputs:
    password: "{{ ddw_password }}"
    username: "{{ ddw_username }}"
    become_method: runas
    become_username: administrator

- name: "{{ my_aap_credential }}"
  organization: "{{ my_organization }}"
  credential_type: Red Hat Ansible Automation Platform
  inputs:
    password: "{{ my_ctrl_admin_password }}"
    username: "{{ my_ctrl_username }}"
    host: "{{ my_aap_url }}"
    # oauth_token: "{{ my_ctrl_admin_oauth_token }}"
    # verify_ssl: true

- name: registry.redhat.io - Ames
  organization: "{{ my_organization }}"
  credential_type: Container Registry
  inputs:
    password: "{{ redhat_passwd }}"
    username: "{{ redhat_username }}"
    host: registry.redhat.io
    verify_ssl: true