---
controller_projects:
- name: aap.dailydemo.F5
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/aap.dailydemo.F5.git

- name: aap.dailydemo.Panos
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/aap.dailydemo.Panos.git

- name: aap.dailydemo.windows
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/aap.dailydemo.windows.git

- name: event.driven.ansible
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/event.driven.ansible.git

- name: aap.dailydemo.linux
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/aap.dailydemo.linux.git

- name: aap.dailydemo.satellite
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/aap.dailydemo.satellite.git

- name: aap.dailydemo.linux
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/aap.dailydemo.linux.git
